name: keyboard_typing
description: "Creates an animation effect where the text appears as if it's being typed on a keyboard."
version: 0.0.2
repository: https://github.com/b3lon9/keyboard_typing

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
